### PR TITLE
Setting version constant in one place

### PR DESCRIPTION
**Pull request by ramourt**
Instead of having the version set in two places, we can rely on webpack to pull the value from package.json and inject it in the constants file during build time.

This makes life easier when bumping versions. Only one value will need to be updated.

### CODE REVIEW

**Comment by erinha** [comment]
<p>Analyzed commit id : 8702057120531aafa86489939f13396f34187685</p><hr><details><summary><b><span style="color: green">⯆</span> @microsoft/bundle-analysis-app:</b> -7 Bytes</summary><table><tr><th>Metric Name</th><th>Baseline Size</th><th>Compare Size</th><th>Size Diff</th></tr><tr><td>main.js</td><td>59.38 KB</td><td>59.37 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr><tr><td>Total Size</td><td>59.38 KB</td><td>59.37 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr></table></details><hr><p>Baseline commit: fc697ff3da1a191a40d7a947afb7f45b50c5e0a6</p>

**Comment by MarcinJuraszek** [comment]
Just to confirm - this does not result in the entire package.json being included in the bundle?

**Review by TrevorJoelHarris — APPROVED** [review]
:shipit:

**Comment by TrevorJoelHarris** [comment]
I approved, but only assuming we are not including the entire package.json file in the bundle. 

---
In reply to: [1005672256](https://github.com/OfficeDev/microsoft-teams-library-js/pull/810#issuecomment-1005672256) [](http://example.com/codeflow?ancestors=1005672256,1005672256)

**Comment by ramourt** [comment]
> Just to confirm - this does not result in the entire package.json being included in the bundle?

@TrevorJoelHarris  @MarcinJuraszek you are correct.
I did a sanity check on the compiled js and it was identical before/after the change.

**Comment by erinha** [comment]
<p>Analyzed commit id : ba4cada4ce7ed815a4724651fe8b932cf358b20d</p><hr><details><summary><b><span style="color: green">⯆</span> @microsoft/bundle-analysis-app:</b> -7 Bytes</summary><table><tr><th>Metric Name</th><th>Baseline Size</th><th>Compare Size</th><th>Size Diff</th></tr><tr><td>main.js</td><td>59.38 KB</td><td>59.37 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr><tr><td>Total Size</td><td>59.38 KB</td><td>59.37 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr></table></details><hr><p>Baseline commit: fc697ff3da1a191a40d7a947afb7f45b50c5e0a6</p>

**Pull request merged**
