### PR TITLE
Revert to registerChangeSettingsHandler

### PR DESCRIPTION
**Pull request by erinha**
This change reverts an accidental rename of an existing API.

This is taking the fix from v1 into v2.

### CODE REVIEW

**Comment by erinha** [comment]
Note: This replaces PR #1144. I had some difficulties trying to update that PR so I am sending out a new one.

**Comment by erinha** [comment]
Note: This replaces PR #1144. I had some difficulties trying to update that PR so I am sending out a new one.

**Review by TrevorJoelHarris — APPROVED** [review]

**Review by AE-MS — DISMISSED** [review]
:shipit:

**Comment by Jessica-Koch** [comment]
ship it! :)

**Review by Jessica-Koch — APPROVED** [review]

**Comment by Jessica-Koch** [comment]
🏖️

**Review by TrevorJoelHarris — APPROVED** [review]

**Review by aeunms — APPROVED** [review]

**Review by AE-MS — APPROVED** [review]
:shipit:

**Pull request merged**
