### PR TITLE
Revert "Restrict updateTask and submitTask to FrameContext.task (#658)"

### PR DESCRIPTION
**Pull request by MarcinJuraszek**
This reverts commit 90a1b0329c209547fd382d820ce6d295f58b45d2.

### CODE REVIEW

**Comment by AE-MS** [comment]
Is there more information about why this change needs to be reverted?

**Comment by MarcinJuraszek** [comment]
It broke Assignments on Teams Mobile.

**Review by AE-MS — APPROVED** [review]
:shipit:

**Review by aeunms — APPROVED** [review]
:shipit:

**Pull request merged**
