### PR TITLE
Surface relevant messaging in bundle analysis comment incase of failures

### PR DESCRIPTION
**Pull request by anmaur**
Incase of known failures in computing bundle analysis, relevant messaging will be posted in the comment and unknown failures will be logged in pipeline.

### CODE REVIEW

**Comment by erinha** [comment]
<p>Analyzed commit id : 2dc2ecb84d45bd81a10b0f50c929ea6d9211256f</p><hr><details><summary><b><span style="color: green">⯆</span> @microsoft/bundle-analysis-app:</b> -7 Bytes</summary><table><tr><th>Metric Name</th><th>Baseline Size</th><th>Compare Size</th><th>Size Diff</th></tr><tr><td>main.js</td><td>59.43 KB</td><td>59.42 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr><tr><td>Total Size</td><td>59.43 KB</td><td>59.42 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr></table></details><hr><p>Baseline commit: 1ae1c726af07ed6f4c9f41264f7c48fe81a558d6</p>

**Review by ramourt — APPROVED** [review]
:shipit:

**Comment by erinha** [comment]
<p>Analyzed commit id : 282d89f582d4af1f20d5ce5cd46f46e904420ed7</p><hr><details><summary><b><span style="color: green">⯆</span> @microsoft/bundle-analysis-app:</b> -7 Bytes</summary><table><tr><th>Metric Name</th><th>Baseline Size</th><th>Compare Size</th><th>Size Diff</th></tr><tr><td>main.js</td><td>59.43 KB</td><td>59.42 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr><tr><td>Total Size</td><td>59.43 KB</td><td>59.42 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr></table></details><hr><p>Baseline commit: 84d8ca3a551852fd526398b97237c56eca7cd2d6</p>

**Comment by erinha** [comment]
<p>Analyzed commit id : 71f70633672ec93a021c6884d7540174faeb343b</p><hr><details><summary><b><span style="color: green">⯆</span> @microsoft/bundle-analysis-app:</b> -7 Bytes</summary><table><tr><th>Metric Name</th><th>Baseline Size</th><th>Compare Size</th><th>Size Diff</th></tr><tr><td>main.js</td><td>59.43 KB</td><td>59.42 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr><tr><td>Total Size</td><td>59.43 KB</td><td>59.42 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr></table></details><hr><p>Baseline commit: f6578fa01b74576079435178cf9cf62a7a3d4e88</p>

**Pull request merged**
