### PR TITLE
Try posting test results to GitHub PRs

### PR DESCRIPTION
**Pull request by MarcinJuraszek**

### CODE REVIEW

**Comment by erinha** [comment]
$(bundleAnalysisTask.bundleAnalysisComment)

**Comment by erinha** [comment]
$(bundleAnalysisTask.bundleAnalysisComment)

**Comment by erinha** [comment]
$(bundleAnalysisTask.bundleAnalysisComment)

**Comment by erinha** [comment]
$(bundleAnalysisTask.bundleAnalysisComment)

**Review by TrevorJoelHarris — APPROVED** [review]
:shipit:

**Pull request merged**
