### PR TITLE
Bug fix on sharing.isSupported() returning true while not supported on mobile

### PR DESCRIPTION
**Pull request by maglims**
For more information about how to contribute to this repo, visit [this page](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/CONTRIBUTING.md).

## Description

During my last DRI session, there was a bug reported on sharing.isSupported() returning true while we can repro that it is not  supported on mobile. The root cause is: if host doesn't send empty object to app sdk during runtime, app sdk will provide a default empty object, meaning that capability is supported. Sharing is in the list of this default setting regardless platform. In this PR, we are removing the default support and instead we start to specify in which version that it gets supported and also provide platform info(currently, sharing is only supported on desktop and web)
> If this Pull Request should close/resolve any issues when merged, use [the special syntax for that](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) here.

### Main changes in the PR:

1. Removing sharing from supported default list
2. Providing a default version on when sharing starts to be supported on desktop and web

### Validation performed:

1. <Step 1>
2. <Step 2>

### Unit Tests added:
Yes, updated existing

### End-to-end tests added:

<Yes/No>

### Change file added:

> Ensure the change file meets the [formatting requirements](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/CONTRIBUTING.md#change-log-using-beachball).

<Yes/No>

### Related PRs:

> Remove this section if n/a

### Next/remaining steps:

> List the next or remaining steps in implementing the overall feature in subsequent PRs (or is the feature 100% complete after this?).

> Remove this section if n/a

- [ ] Item 1
- [ ] Item 2

### Screenshots:

> Remove this section if n/a

| Before     | After      |
| ---------- | ---------- |
| < image1 > | < image2 > |

### CODE REVIEW

**Review by TrevorJoelHarris — DISMISSED** [review]

**Comment by AE-MS** [comment]
>   '2.0.1': [

Does any version of Teams desktop (Angular or React) pass a "clientSupportedSDKVersion" in response to the `initialize` call? If so, what version do they pass?

---
Refers to: packages/teams-js/src/public/runtime.ts:311 in 46c2e22. [](commit_id = 46c2e226494cca25369f66192f0e3b8e073eae49, deletion_comment = False)

**Review by AE-MS — CHANGES_REQUESTED** [review]
:clock1:

**Comment by AE-MS** [comment]
>   '2.0.1': [

I looked into it. It seems like Angular Teams (pre-host SDK) doesn't pass a version at all, so it will be 2.0.1 in that case (since that's the default version this library assumes when no version is returned from the initialize call).

However, React Teams, which has integrated with the host SDK, looks like it will return 2.0.0 since that's what the host SDK returns (see the link I sent you). That makes me think that this addition needs to go in to the 2.0.0 section otherwise it won't work in React Teams and only Angular Teams.

---
In reply to: [1462540334](https://github.com/OfficeDev/microsoft-teams-library-js/pull/1636#issuecomment-1462540334) [](http://example.com/codeflow?ancestors=1462540334)

---
Refers to: packages/teams-js/src/public/runtime.ts:311 in 46c2e22. [](commit_id = 46c2e226494cca25369f66192f0e3b8e073eae49, deletion_comment = False)

**Comment by AE-MS** [comment]
> describe('sharing_v1', () => {

Should there be tests which validate that when the client type is returned from the init call is mobile that sharing is not supported? And that it is supported for the versions we expect when not on mobile?

---
Refers to: packages/teams-js/test/public/sharing.spec.ts:13 in 46c2e22. [](commit_id = 46c2e226494cca25369f66192f0e3b8e073eae49, deletion_comment = False)

**Comment by maglims** [comment]
> > describe('sharing_v1', () => {
> 
> Should there be tests which validate that when the client type is returned from the init call is mobile that sharing is not supported? And that it is supported for the versions we expect when not on mobile?
> 
> Refers to: packages/teams-js/test/public/sharing.spec.ts:13 in [46c2e22](https://github.com/OfficeDev/microsoft-teams-library-js/commit/46c2e226494cca25369f66192f0e3b8e073eae49). [](commit_id = [46c2e22](https://github.com/OfficeDev/microsoft-teams-library-js/commit/46c2e226494cca25369f66192f0e3b8e073eae49), deletion_comment = False)

**Comment by maglims** [comment]
> > > describe('sharing_v1', () => {
> > 
> > 
> > Should there be tests which validate that when the client type is returned from the init call is mobile that sharing is not supported? And that it is supported for the versions we expect when not on mobile?
> > Refers to: packages/teams-js/test/public/sharing.spec.ts:13 in [46c2e22](https://github.com/OfficeDev/microsoft-teams-library-js/commit/46c2e226494cca25369f66192f0e3b8e073eae49). [](commit_id = [46c2e22](https://github.com/OfficeDev/microsoft-teams-library-js/commit/46c2e226494cca25369f66192f0e3b8e073eae49), deletion_comment = False)

Great suggestions! thanks

**Review by TrevorJoelHarris — APPROVED** [review]

**Review by AE-MS — APPROVED** [review]
:shipit:

**Pull request merged**
