### PR TITLE
Kx/change titles for iOS UI tests

### PR DESCRIPTION
**Pull request by KangxuanYe**
## Description

Change some of titles in test App:
1. 'location' to 'geoLocation' under geoLocationAPIs.2. 
2. 'shareDeepLink's to be either 'shareDeepLink (Core)' or 'shareDeepLink (Pages)' 
as it's hard to do UI Test Apps if there are duplicate names.

### Main changes in the PR:

1. 'location' to 'geoLocation' under geoLocationAPIs file.
2. shareDeepLink's to be either 'shareDeepLink (Core)' or 'shareDeepLink (Pages)'  in PagesAPIs file

## Validation
build successfully and checked by eyes.

### Unit Tests added: No

Only displayed titles are changed.

### Change file added: No

### CODE REVIEW

**Comment by MarcinJuraszek** [comment]
Shouldn't any automation trying to interact with the Test App use element Ids and not text within them?

**Review by lakhveerk — APPROVED** [review]
LGTM

**Comment by KangxuanYe** [comment]
> 

iOS UI Test cannot support that, i.e. finding ui elements by resource id, and everything would be text/location related.
In the other word, iOS UI test is strict on UI layout (what the view looks like).

**Review by aeunms — COMMENTED** [review]
:shipit:

**Review by aeunms — APPROVED** [review]
oops, just commented last time. Approved!

**Pull request merged**
