### PR TITLE
Update last batch of APIs to the new test app components

### PR DESCRIPTION
**Pull request by MarcinJuraszek**

### CODE REVIEW

**Comment by erinha** [comment]
<p>Analyzed commit id : a25b5c0c9565f59c03f8cd564802fb6ea03547a0</p><hr><details><summary><b><span style="color: green">⯆</span> @microsoft/bundle-analysis-app:</b> -6 Bytes</summary><table><tr><th>Metric Name</th><th>Baseline Size</th><th>Compare Size</th><th>Size Diff</th></tr><tr><td>main.js</td><td>58.4 KB</td><td>58.4 KB</td><td><span style="color: green">⯆</span> -6 Bytes</td></tr><tr><td>Total Size</td><td>58.4 KB</td><td>58.4 KB</td><td><span style="color: green">⯆</span> -6 Bytes</td></tr></table></details><hr><p>Baseline commit: 6df141a55c7cfc851561f37257ac299402bb2e7b</p>

**Comment by erinha** [comment]
<p>Analyzed commit id : a25b5c0c9565f59c03f8cd564802fb6ea03547a0</p><hr><details><summary><b><span style="color: green">⯆</span> @microsoft/bundle-analysis-app:</b> -6 Bytes</summary><table><tr><th>Metric Name</th><th>Baseline Size</th><th>Compare Size</th><th>Size Diff</th></tr><tr><td>main.js</td><td>58.4 KB</td><td>58.4 KB</td><td><span style="color: green">⯆</span> -6 Bytes</td></tr><tr><td>Total Size</td><td>58.4 KB</td><td>58.4 KB</td><td><span style="color: green">⯆</span> -6 Bytes</td></tr></table></details><hr><p>Baseline commit: 6df141a55c7cfc851561f37257ac299402bb2e7b</p>

**Comment by erinha** [comment]
<p>Analyzed commit id : a25b5c0c9565f59c03f8cd564802fb6ea03547a0</p><hr><details><summary><b><span style="color: green">⯆</span> @microsoft/bundle-analysis-app:</b> -6 Bytes</summary><table><tr><th>Metric Name</th><th>Baseline Size</th><th>Compare Size</th><th>Size Diff</th></tr><tr><td>main.js</td><td>58.4 KB</td><td>58.4 KB</td><td><span style="color: green">⯆</span> -6 Bytes</td></tr><tr><td>Total Size</td><td>58.4 KB</td><td>58.4 KB</td><td><span style="color: green">⯆</span> -6 Bytes</td></tr></table></details><hr><p>Baseline commit: 6df141a55c7cfc851561f37257ac299402bb2e7b</p>

**Review by anmaur — APPROVED** [review]
Looks good to me!!

**Pull request merged**
