### PR TITLE
Remove bot capability

### PR DESCRIPTION
**Pull request by MarcinJuraszek**

### CODE REVIEW

**Review by jadahiya-MSFT — APPROVED** [review]

**Review by jadahiya-MSFT — DISMISSED** [review]

**Review by erinha — APPROVED** [review]
:shipit:

**Review by aeunms — COMMENTED** [review]
Should we also edit src/public/runtime.ts and any other files that deal with bot capability support in this PR?

**Review by ydogandjiev — APPROVED** [review]

**Comment by MarcinJuraszek** [comment]
> Should we also edit src/public/runtime.ts and any other files that deal with bot capability support in this PR?

Good catch!

**Review by aeunms — APPROVED** [review]
LGTM!

**Review by erinha — APPROVED** [review]
🚀

**Pull request merged**
