### PR TITLE
Hide the new meeting audio APIs from documentation, and update test app

### PR DESCRIPTION
**Pull request by thomasnakagawa**
## Description
Follow-up to #1436 

Adds the `@hidden` and `@internal` tags to the functions and interfaces for the `requestAppAudioHandling` and `updateMicState` APIs.

Also updates the test app to work better with the E2E tests

As discussed, we're adding these tags because these APIs are meant to be used for a very limited use-case.

### Main changes in the PR:

- Added `@hidden` and `@internal` tags to the comments for the new meeting audio APIs so they're excluded from the documentation.
- Updated the teams-test-app for the new meeting audio APIs so they're more consistent with how the app handles the rest of the APIs, which helps the E2E tests run better

### Validation performed:

Ran `yarn build` and `yarn test` just to be sure

### Unit Tests added:

None added, changes are in comments only

### End-to-end tests added:

No

### Change file added:

~~Ran beachball, it said no changelog is needed for these changes.~~ Added a patch changelog file

### Related PRs:

#1436

### CODE REVIEW

**Review by TrevorJoelHarris — APPROVED** [review]

**Review by AE-MS — DISMISSED** [review]

**Review by TrevorJoelHarris — CHANGES_REQUESTED** [review]
You'll need to generate a changefile for this before you can check in. Instructions and style guidelines can be found here: https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/CONTRIBUTING.md

**Comment by thomasnakagawa** [comment]
> @thomasnakagawa please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@microsoft-github-policy-service agree [company="microsoft"]

**Comment by thomasnakagawa** [comment]
@microsoft-github-policy-service agree company="microsoft"

**Comment by thomasnakagawa** [comment]
@microsoft-github-policy-service agree

**Review by AE-MS — DISMISSED** [review]

**Review by TrevorJoelHarris — APPROVED** [review]

**Review by AE-MS — APPROVED** [review]
:shipit:

**Pull request merged**
