### PR TITLE
Change video.EffectChangeType to string enum

### PR DESCRIPTION
**Pull request by WengHe**
## Description

Changed `video.EffectChangeType` to string enum

### Unit Tests added:

No

### End-to-end tests added:

No

### Change file added:

Yes

### CODE REVIEW

**Review by lubobill1990 — APPROVED** [review]

**Comment by nandin-borjigin** [comment]
Please revise the PR title as ErrorLevel change is reverted

**Comment by erinha** [comment]
This PR title says it's updating code in videoEx.ts, but I see no changes in that file.

**Review by TrevorJoelHarris — APPROVED** [review]

**Review by TrevorJoelHarris — APPROVED** [review]

**Review by erinha — APPROVED** [review]

**Pull request merged**
