### PR TITLE
Replaced exec/execSync with execFile and execFileSync

### PR DESCRIPTION
**Pull request by jadahiya-MSFT**
For more information about how to contribute to this repo, visit [this page](https://github.com/OfficeDev/microsoft-teams-library-js/blob/main/CONTRIBUTING.md).

## Description

> Summarize the changes, including the goals and reasons for this change. Be sure to call out any technical or behavior changes that reviewers should be aware of.

> If this Pull Request should close/resolve any issues when merged, use [the special syntax for that](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) here.

### Main changes in the PR:

1. Replaced exec and execSync to execFile and execFileSync to prevent any additional user commands from being injected into this code execution

### Validation performed:

1. Manually tested user code injection on exec/execSync vs execFile and execFileSync, the former allowed for my simple "hello" statement to be injected while the latter did not.

### CODE REVIEW

**Review by noahdarveau-MSFT — APPROVED** [review]

**Comment by AE-MS** [comment]
In the future, filling out the PR description template will help provide information to reviewers they can use as they review. Thank you.  :)

**Comment by AE-MS** [comment]
Can you describe the motivation for this change? Is exec/execSync bad?

**Comment by AE-MS** [comment]
What kind of validation do we have for this code?

**Review by AE-MS — CHANGES_REQUESTED** [review]
:clock1:

**Comment by noahdarveau-MSFT** [comment]
Can you explain how execFile is preventing injection. My understanding is that execFile, while running with the shell option, is functioning the same exec.

**Comment by jadahiya-MSFT** [comment]
> Can you explain how execFile is preventing injection. My understanding is that execFile, while running with the shell option, is functioning the same exec.

Good catch, I'm going to update this with a new way of calling these functions

**Comment by TrevorJoelHarris** [comment]
@jadahiya-MSFT is this still intended for checkin, or should the PR be closed?

**Pull request closed without merging**
