### PR TITLE
Merge from upstream (TeamsJS v1 aka master branch) Dec 8, 2021

### PR DESCRIPTION
**Pull request by aeunms**
New function(s) for the test app will come in on the next PR. Wanted to put this one out first as it ran a bit long while I was out sick.

### CODE REVIEW

**Comment by erinha** [comment]
$(bundleAnalysisTask.bundleAnalysisComment)

**Comment by erinha** [comment]
$(bundleAnalysisTask.bundleAnalysisComment)

**Comment by erinha** [comment]
$(bundleAnalysisTask.bundleAnalysisComment)

**Review by erinha — APPROVED** [review]
LGTM, thanks!

**Comment by erinha** [comment]
$(bundleAnalysisTask.bundleAnalysisComment)

**Comment by aeunms** [comment]
Closing this out since it got so long and it shouldn't be squash merged to conserve master history. Will start another PR with cleaner history

**Pull request closed without merging**
