### PR TITLE
Util for backwards compatibility mode in the Test App

### PR DESCRIPTION
**Pull request by jadahiya-MSFT**
Added in a url parameter that is passed in via the Orange Hub to determine whether to run the teams test app in backwards compatibility mode or not.

### CODE REVIEW

**Comment by erinha** [comment]
<p>Analyzed commit id : e1d77f49bc33c8222bb960b84018c390a26a0787</p><hr><details><summary><b><span style="color: green">⯆</span> @microsoft/bundle-analysis-app:</b> -7 Bytes</summary><table><tr><th>Metric Name</th><th>Baseline Size</th><th>Compare Size</th><th>Size Diff</th></tr><tr><td>main.js</td><td>59.43 KB</td><td>59.42 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr><tr><td>Total Size</td><td>59.43 KB</td><td>59.42 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr></table></details><hr><p>Baseline commit: 84d8ca3a551852fd526398b97237c56eca7cd2d6</p>

**Comment by erinha** [comment]
<p>Analyzed commit id : 6c2b24c773b3a6e86015b8c5667e3f7a835a8f22</p><hr><details><summary><b><span style="color: green">⯆</span> @microsoft/bundle-analysis-app:</b> -7 Bytes</summary><table><tr><th>Metric Name</th><th>Baseline Size</th><th>Compare Size</th><th>Size Diff</th></tr><tr><td>main.js</td><td>59.43 KB</td><td>59.42 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr><tr><td>Total Size</td><td>59.43 KB</td><td>59.42 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr></table></details><hr><p>Baseline commit: 84d8ca3a551852fd526398b97237c56eca7cd2d6</p>

**Comment by erinha** [comment]
<p>Analyzed commit id : 887769606b901d04083d8e0612d24cadf51cb9b9</p><hr><details><summary><b><span style="color: green">⯆</span> @microsoft/bundle-analysis-app:</b> -7 Bytes</summary><table><tr><th>Metric Name</th><th>Baseline Size</th><th>Compare Size</th><th>Size Diff</th></tr><tr><td>main.js</td><td>59.43 KB</td><td>59.42 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr><tr><td>Total Size</td><td>59.43 KB</td><td>59.42 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr></table></details><hr><p>Baseline commit: f6578fa01b74576079435178cf9cf62a7a3d4e88</p>

**Review by MarcinJuraszek — APPROVED** [review]

**Comment by erinha** [comment]
<p>Analyzed commit id : eeea8f36d472b0ae528fa1242bb1bcb758b10dc4</p><hr><details><summary><b><span style="color: green">⯆</span> @microsoft/bundle-analysis-app:</b> -7 Bytes</summary><table><tr><th>Metric Name</th><th>Baseline Size</th><th>Compare Size</th><th>Size Diff</th></tr><tr><td>main.js</td><td>59.43 KB</td><td>59.42 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr><tr><td>Total Size</td><td>59.43 KB</td><td>59.42 KB</td><td><span style="color: green">⯆</span> -7 Bytes</td></tr></table></details><hr><p>Baseline commit: 247aa802c407b894cd515b6a838bf15db5b279a0</p>

**Pull request merged**
