### PR TITLE
Update postrelease pipeline to trigger actions of TeamsFx repo

### PR DESCRIPTION
**Pull request by tecton**
Use repository dispatch to trigger GitHub Action in TeamsFx repo. It helps to notify developers of the latest release version.

Secret to add: `TEAMSFX_REPO_ACCESS_TOKEN`

### CODE REVIEW

**Comment by AE-MS** [comment]
If this timeline is okay with you, @erinha will review this on Thursday.

**Review by erinha — APPROVED** [review]

**Review by lakhveerk — APPROVED** [review]

**Pull request merged**
